### ISSUE TITLE
Docstring failure on exported functions

### ISSUE THREAD

**Issue by multidis** [MichaelHatherly/Lexicon.jl#112] opened 2015-05-19 20:18 UTC
Trying to generate documentation as [described here](http://tradinglogicjl.readthedocs.org/en/latest/notes.html#developer-notes), and after some complicated text output [api.md](https://github.com/JuliaQuant/TradingLogic.jl/blob/master/docs/api.md) is generated without exported functions `runtrading!` and `tradeperf`.

A bug or is something unacceptable written within those functions' docstrings?

**Comment by MichaelHatherly** [comment] 2015-05-19 20:59
> A bug or is something unacceptable written within those functions' docstrings?

It's a bug in Docile's ``Method`` finding code. Your docstrings are fine :)

I recently switched to a new method for finding which methods are associated with which docstrings based on their file/line info rather than looking at the signatures. Since the signatures for ``runtrading!`` and ``tradeperf`` extend over multiple lines their associated line info doesn't match what Docile is looking for. (`90` instead of `89` for ``tradingperf`` and `71` instead of `65` for ``runtrading!``.)

I've got a fix in mind which I'll try to get implemented tomorrow if time allows.

> after some complicated text output

I've been trying to gauge how much output Docile should be providing to users. Do you feel it's a bit too much?

Side note: with the way Docile works now you can remove the ``using Docile`` and ``@document`` and it'll still find the docstrings when generating static docs or searching at the REPL.

**Comment by multidis** [comment] 2015-05-19 22:45
> I've been trying to gauge how much output Docile should be providing to users. Do you feel it's a bit too much?

For me the optimal amount of output would be just the names of functions (one per line) where some docstring is found and is being parsed. That would help to spot if something is not right with methods vs. functions documentation. Anything else would be needed only if there are errors.

>Side note: with the way Docile works now you can remove the using Docile and @document and it'll still find the docstrings when generating static docs or searching at the REPL.

This is **very helpful** not to require `Docile` package dependency in production, thanks for pointing out! I have been manually commenting those lines in and out for documentation generation...

**Comment by MichaelHatherly** [comment] 2015-05-20 12:26
Fixed in https://github.com/MichaelHatherly/Docile.jl/commit/5497f313125f58dc8f08a3a2126442693e879017. I've tested that Docile now picks up ``runtrading!`` and ``tradeperf`` methods as documented. Could you checkout Docile ``master`` to confirm? I'll tag a patch release if all is well.

> That would help to spot if something is not right with methods vs. functions documentation.

The simplest way at the moment to check what is documented without having to run ``Lexicon.save`` is with

```
julia> using TradingLogic, Docile

julia> Docile.Cache.getraw(TradingLogic)
Docile: updating package list…
Docile: caching 'TradingLogic'…
 - TradingLogic ✓
ObjectIdDict with 44 entries:

... lots of output ...

```

which will show you what Docile has managed to find in ``TradingLogic``. I'm planning to add additional features to ``Lexicon.doctest`` to hopefully automate some of this kind of debugging at some point though.

**Comment by multidis** [comment] 2015-05-20 18:55
Tested with Docile master, everytning seems to be parsed correctly. Also checked with a private package that had similar docstring difficulties and that one is fine as well.

One thing I noticed is that documentation for a function and its methods comes out in different places in the md-output (`tradepnlfinal` in `TradingLogic.jl` case). Is that by design to separate out functions and methods or is it just because a dictionary of the type that shows up with `Docile.Cache.getraw` does not undergo key sorting?

**Comment by MichaelHatherly** [comment] 2015-05-20 19:31
> Tested with Docile master, everytning seems to be parsed correctly. Also checked with a private package that had similar docstring difficulties and that one is fine as well.

Great, thanks. I'll tag a patch a little later this evening.

> Is that by design to separate out functions and methods or is it just because a dictionary of the type that shows up with `Docile.Cache.getraw` does not undergo key sorting?

It's currently like this by design. It's been bothering me recently so I'll probably look into improving things for Lexicon `0.2`.

Displaying the `Function` docstring followed by any additional `Method` docstrings as a single unit seems like the best way to go and might solve the problem of long method signatures being difficult to read as well.

This wouldn't change any of Docile's internal storage and would just be on the Lexicon frontend. The `ObjectIdDict` will remain unsorted.

**Closed by MichaelHatherly** 2015-05-20 19:31 UTC
Labels: bug

**Comment by peter1000** [comment] 2015-06-03 09:23
> The ObjectIdDict will remain unsorted.

for julia 0.4 there is a discussion to include an ordered dict: https://github.com/JuliaLang/julia/pull/10116 not sure if the final version will also effect: ObjectIdDict
